---
name: vmklib
version: "{{major}}.{{minor}}.{{patch}}"
description: "Simplify project workflows by standardizing use of GNU Make."
entry: {{entry}}

requirements:
  - vcorelib>=0.11.3

dev_requirements:
  - pytest-asyncio
  - setuptools-wrapper

keywords:
  - workflow
  - tool
  - make

classifiers:
  - "Topic :: Software Development :: Build Tools"
