---
name: vmklib
version: "{{major}}.{{minor}}.{{patch}}"
description: "Simplify project workflows by standardizing use of GNU Make."
entry: {{entry}}

requirements:
  - vcorelib>=3.4.3

  # Adding this dependency simplifies project-specific workflow integrations
  # that leverage interfaces from this package.
  - experimental-lowqa

dev_requirements:
  - pytest-asyncio
  - setuptools-wrapper

keywords:
  - workflow
  - tool
  - make

classifiers:
  - "Topic :: Software Development :: Build Tools"
